### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by zhangguobing** [AlexMofer/Printer#1]
你好，我这里在使用蓝牙打印机时出现一个问题，就是有时候打印不完整，少打印了几行数据，而数据我明明已经写进去了。不知道你有没有遇到过这种情况

**Comment by AlexMofer** [comment]
我没有遇到过，是必现的Bug还是偶尔出现？你可以把样例发给我看看，我可以以试试公司两台蓝牙打印机是否有这一问题。

**Comment by zhangguobing** [comment]
是必现的bug。这是程序的问题吗，还是打印机的 问题

**Comment by zhangguobing** [comment]
经过测试发现，我这里有好几种小票嘛，好像就其中一种小票有这问题，好奇怪

**Comment by AlexMofer** [comment]
在最后一行数据后面多加几个换行命令，最后再加一个进纸切割命令，看试试还有问题没有。要确认是否是打印机问题的话，你可以拿多台打印机测试。

**Comment by zhangguobing** [comment]
这好像是调用写入数据的时机不同引起的，我用之前的先得到连接再写数据的方式没这问题

**Comment by AlexMofer** [comment]
那就有可能是数据提交没有全部完成导致的。
后续我会完善一下这个项目，因为我的项目全部放在[ProjectX](https://github.com/AlexMofer/ProjectX)里面管理，你可参考一下这个项目里的打印样例，其实整套代码你只需要实现小票排版跟打印回调就行了，主要传入IP端口或者BluetoothDevice以及小票类型就可以了。
样例：[PrinterData.java](https://github.com/AlexMofer/ProjectX/blob/master/app/src/main/java/am/project/x/activities/util/printer/data/PrinterData.java)：小票排版。
[PrinterTester.java](https://github.com/AlexMofer/ProjectX/blob/master/app/src/main/java/am/project/x/activities/util/printer/data/PrinterTester.java)打印请求处理及回调。
