### ISSUE TITLE
what possible values for 'type' when calling new PrintExecutor(String ip, int port, int type) ?

### ISSUE THREAD

**Issue by erlangparasu** [AlexMofer/Printer#10]
@AlexMofer

**Comment by AlexMofer** [comment]
Any value is OK.
It as a param send back to PrintDataMaker#getPrintData(int type), so there you can get you 'type' values, to use it create PrinterWriter58mm, PrinterWriter80mm or your custom PrinterWriter.
If you just use one kind of PrinterWriter. Ignore it.
It design for user, we give those type values to select which kind of PrinterWriter.

**Comment by erlangparasu** [comment]
ow.. thanks sir :) :+1:
