### ISSUE TITLE
请问打印图片会出现卡顿怎么解决

### ISSUE THREAD

**Issue by qianmang2** [AlexMofer/Printer#11]

**Comment by AlexMofer** [comment]
一般小票热敏打印机缓存都很小，只要不是打印过大的图片，基本上100x100左右的都能流畅打印。但还是存在一些没法流畅打印，甚至没法打印，可以测试一下是否为图片过大导致，改用小图试试，小图还不行，那就没辙了。之前项目上五六台打印机，就一台遇到过，无论打印什么图片，多大多小，都会导致打印图片时卡住不走了，仅仅只能打印文字。一般来说，不是便宜的离谱的机子，基本没有问题。也没有解决方案，硬件限制。不得不提供一个开关，用于开关过滤图片让用户自己选择（默认开启）。

**Comment by AlexMofer** [comment]
如果是图片过大导致，可以将图片高度分割值调小，分多次打印。或者尝试socket分多次提交数据。

**Comment by qianmang2** [comment]
非常感谢，我把图片宽度调成200后（之前是300）就不卡顿了。
