### ISSUE TITLE
图片居中问题

### ISSUE THREAD

**Issue by byte-art** [AlexMofer/Printer#13]
直接运行项目，打印的图片和上面的二维码不是居中的，我自己使用项目上的打印代码，打印图片也不是居中，已经setAlign了

**Comment by AlexMofer** [comment]
这份代码我测试过不低于5台小票打印机，仅遇到过一台只要有图片都无法打印的小票打印机。目前都未遇到过你说的图片不剧中问题。你需要确认一下以下几点：
1. 是否是小票打印机的问题。如果手头有其他打印机，尝试换一台小票打印机打印。
2. 确认是仅仅图片无法居中还是文字与图片都无法剧中。
3. 确认是否剧中效果仅仅对图片无效，设置剧中，打印图片，换行，再打印一段文字，换行，设置左对齐，打印图片，换行，再打印一段文字，换行，设置右对齐，打印图片，换行，再打印一段文字。检验文字跟图片的对齐情况。
4.确保你的图片有效显示区域占满图片区域，不要有图片一端有一大片透明，（图片有效区域本身就不剧中）。

最后：本人手头已无小票打印机用于测试，因此无法帮你检查。仅仅能帮你从逻辑上判断。源码使用的均为ESC/POS标准指令，但并不是所有小票打印机都严格遵循（一般来说都支持）。且并非所有小票打印机都能有效按照预期实现效果。如字体大小偏差，行间距高宽偏差，字符集问题等等。该工具包仅把指令变成可阅读性较好的方法。目前项目对齐方式使用的是“ESC a n”中的0（左）、1（中）、2（右）。你可以尝试使用另一组参数：48（左）、49（中）、50（右）。

```java
    /**
     * Aligns all the data in one line to the specified position
     * n selects the justification as follows:
     * n=0,48 : Left justification
     * n=1,49 : Centering
     * n=2,50 : Right justification
     * ESC a n
     *
     * @param n 0≤n≤2,48≤n≤50 default 0
     * @return command
     */
    public static byte[] selectJustification(int n) {
        return new byte[]{ESC, 97, (byte) n};
    }
```

**Comment by byte-art** [comment]
好的，谢谢你的答复

**Comment by wuhaiyang** [comment]
@AlexMofer  0≤n≤2,48≤n≤50两种指令都试过了，在芯烨(XINYE)XP-P300 (58mm) 机器上 图片居左、居右、居中都无效。 文字能居中

**Comment by AlexMofer** [comment]
@wuhaiyang 确保你的图片足够小，如果你图片大过打印纸的面积也是无法居中的。如果图片大小合适，但还是无法居中，那么该打印机以项目中的打印图片的方式打印时忽略了对其方式。尝试使用其他的图片打印方式，或者如果是固定图片，制作一张占满58mm的宽度的图片，两边留白，这样也是居中的，如果是不固定图片，如二维码，你可以用Bitmap拓展出一张占满且两边留白的图片。其他更好的方式待你自行发现。

**Comment by wuhaiyang** [comment]
谢了
