### ISSUE TITLE
用demo连接热敏打印机，第一次打印时很慢，或者直接失败。

### ISSUE THREAD

**Issue by KomoriWu** [AlexMofer/Printer#14]
但是成功一次之后，后面就很顺畅了。
这是因为打印机原因还是？
或者我们能知道打印失败的回调吗？
谢谢，很急。

**Comment by AlexMofer** [comment]
状态改变跟打印结果都有监听，建议你把打印图片的部分代码屏蔽再试试。

**Comment by KomoriWu** [comment]
一样的还是老问题，第一次会卡住很半天。demo到“获取输出流成功，开始写入测试页面数据”就卡着不动了，接下来也没有回调。大神求解。

**Comment by AlexMofer** [comment]
打印机缓存小，如果你是run项目的话，把图片打印部分的代码注释掉，只打印文字不打印图片，大概率就不会卡了。这种要么不打印图片，要么就自行调整输出流的写入方式，或者分段打印。总之就是，写入输出数据不能太大，需要写入较多的输出数据时，分多个批次写入。

**Comment by 1771300336** [comment]
大佬,这个还在搞么。我这也运行demo就打印一行字   到“获取输出流成功，开始写入测试页面数据”就卡着不动了，一点反应也没有。

**Comment by AlexMofer** [comment]
@1771300336 直接拉下来就跑的程序吗？你把写入数据中打印图片相关的代码去掉试试。有些廉价打印机没法正常打印图片。

**Comment by 1771300336** [comment]
DateMaker里图片的都注掉了,就剩两行打印文字的, 状态只是显示到     获取输出流成功，开始写入测试页面数据

**Comment by AlexMofer** [comment]
@1771300336 写入测试流出错,这是网络请求这一块的问题,你可以手动自己写一个Socket进行数据发送.我这边没有打印设备,没法测试了.
