### ISSUE TITLE
打印图片问题

### ISSUE THREAD

**Issue by qianmang2** [AlexMofer/Printer#15]
当我正在打印图片的时候，我关闭了这个Activity，我也在onDestory()方法里调用了closeSocket()方法，就会出现打印乱码。

**Comment by AlexMofer** [comment]
虽然图片是分成一小块一小块打印，但当一小块图片数据还未传输完毕，你就关闭Socket，这时候，打印机只接收到部分数据也没收到重置信号，因此他会打印出一堆乱码。这也是为什么有些打印机可以一次性打印一张大图，而有些只能切割成很小一块才能打印。数据缓冲区被写满，就如同你的传输被断开，都是数据不全导致，结果就是打印乱码（把它当作字符来打印）。

**Comment by qianmang2** [comment]
那我在图片还没打印完图片，就离开这个Activity，为了保证不乱码该怎么做呢？

**Comment by qianmang2** [comment]
在我打印图片的时候，在手机系统设置里关闭蓝牙，就没打印了。但我仅仅只是停止打印，不想把系统蓝牙给关闭了。

**Comment by AlexMofer** [comment]
试试在关闭Socket之前停止传输图片数据，此时再发送打印机重置命令，再关闭Socket。
