### ISSUE TITLE
Support Chinese, Japanese

### ISSUE THREAD

**Issue by samk17cmutpm** [AlexMofer/Printer#18]
Hi mate, I have tried Chinese and Japanese. It didn't work. 
Could you help me out!

![PXL_20210301_042550403](https://user-images.githubusercontent.com/7029528/109451869-0f3da480-7a81-11eb-902f-2405a36cbdc6.jpg)

**Comment by AlexMofer** [comment]
貌似不是程序问题，打印机不具备中日韩字符集。所以遇到中日韩字符全部乱码了。

**Comment by AlexMofer** [comment]
CJK fonts are not installed in the printer.
