### ISSUE TITLE
android6.0打印二维码异常

### ISSUE THREAD

**Issue by zhangguobing** [AlexMofer/Printer#2]
我这里android6.0打印二维码异常，都是乱的

**Comment by AlexMofer** [comment]
我用的开发机子就是6.0的Nexus 5X，没有问题，目前升级到7.0也是没有问题，你用的是Drawable方式还是生成Bitmap方式？

**Comment by zhangguobing** [comment]
bitmap方式

**Comment by AlexMofer** [comment]
我排查一下问题。

**Comment by AlexMofer** [comment]
我这边排查结果是：
bitmap方式：
Nexus 5X、Andorid 7.0、IP提交方式  、ZXing生成二维码、Bitmap方式           测试通过
SUNMI V1、Android 5.1、蓝牙提交方式  、ZXing生成二维码、Bitmap方式           测试通过
SM-G900F、Android 6.0.1、IP提交方式  、ZXing生成二维码、Bitmap方式           测试通过
商米是蓝牙一体机，没法用其他设备测试，蓝牙提交方式你得自己测试一下，你clone这个项目（Printer）到本地跑一下看是否存在问题，如果有问题我再看看，如果没有问题，那你得检查一下看是否是打印数据提交方式有问题了。

**Comment by zhangguobing** [comment]
有的手机打印出来的二维码图片过大，请问有没有办法可以处理

**Comment by zhangguobing** [comment]
有没有办法做到让二维码图片的占纸宽的百分之多少

**Comment by zhangguobing** [comment]
有没有办法做到让二维码图片的大小占纸宽的百分之多少

**Comment by zhangguobing** [comment]
如果我在zxing生成二维码图时设置四周留空白区域，打印出来就会显示不全

**Comment by zhangguobing** [comment]
float scale = 1;
if (maxWidth <= 0 || width <= maxWidth) {
    scale = maxWidth / (float) width;
 } 好像是这行代码出的问题，如果width比maxWidth大，就不会scale

**Comment by AlexMofer** [comment]
decodeBitmap(Bitmap image)方法只会在你的Bitmap宽度超过2040时进行缩小到2040，8位9针打印方式的限制问题，但其实一般小票打印都没法完全显示那么大的图，但是不影响打印。一般80mm的小票打印机最大能够显示的图片宽度为500，58mm的为380，建议你根据纸张类型来缩放bitmap。知道大致的最大宽度的话，你用来计算百分比也就不是难事了。四周留空白其实不是关键点，关键点是你创建的Bitmap是否足够装下二维码的所有像素点。
