### ISSUE TITLE
请问一下，总出现创建Socket失败，是什么原因呢？

### ISSUE THREAD

**Issue by loren0222** [AlexMofer/Printer#5]
有时间是日志输出 开始创建Socket连接…  就没有反应了，

**Comment by AlexMofer** [comment]
是偶发还是一直都是出现？有没有使用demo尝试打印？是蓝牙还是固定IP？有没有尝试修改打印机IP？你可以自行创建Socket连接测试一下是否创建连接存在问题，你可以通过PrinterWriter的子类来获取所有需要上传的byte数据流，你可以自行建立网络连接进行上传。具体原因具体分析，如果不抛出异常那么就是网络存在问题了。

**Comment by loren0222** [comment]
您好，我是用的蓝牙，demo测试了没有问题,方便留个QQ或者微信吗？

**Comment by AlexMofer** [comment]
那应该是你在建立连接的时候出问题了，检查一下代码。QQ：763270412，不是经常有空。

**Comment by qianmang2** [comment]
你可能在同一个页面创建了多个PrintExecutor对象。
