### ISSUE TITLE
有一些字符不知道你能不能打印

### ISSUE THREAD

**Issue by tmyzh13** [AlexMofer/Printer#6]
ÄÖÜßn°€éè  我需要打印这些字符，我想的是设置字符集来处理，但是没成功，不知道你有没有解决办法

**Comment by AlexMofer** [comment]
这种字符的不支持，貌似不是软件上能解决的，便宜的打印机一般只有一种字符集，为了降低价格减少存储控件，往往厂商会把很多很少用到的特殊字符删掉，硬件的不支持，软件上是无解的，除非你直接打印文字图片。

**Comment by tmyzh13** [comment]
谢谢您的回复，问过您之后我也是在找这方面的资料，这个说法我觉得是可能的，但是其实后面我发现的我面临的其实是另一个问题，打印utf-8的数据和GBK的数据，UTF-8的会出问题，乱码，以前在自带打印机的pos机上处理过，设置了字符集指令（1c 43 ff），但是现在在打印机上设置了没用，您处理过这样的问题吗

**Comment by AlexMofer** [comment]
没有遇到这样的问题，按照我的理解，修改字符集仅仅是修改了可打印的字符范围，有些打印机支持，有些不支持。而使用UTF-8编码模式来传递数据出现乱码，如果只是部分字符出现乱码，那么也就是字符不全导致的问题，而如果是全部乱码，那就是打印机并不认这种编码格式，那么就得考虑将UTF-8编码模式转换成GBK模式再传递数据。通用的代价就是各种兼容问题，而接入SDK的问题就是包体巨大，只能取舍，尽量满足需求。希望能帮助到你。
