### ISSUE TITLE
蓝牙票机配合handler会出现打印失败

### ISSUE THREAD

**Issue by thundeGG** [AlexMofer/Printer#8]
您好，打扰您了，我用您的库发现一个问题
```
for (int i = 0; i <5; i++) {
                PrintExecutor executor = new PrintExecutor(mDevice, type);
                executor.setOnStateChangedListener(this);
                executor.setOnPrintResultListener(this);
                executor.setDevice(mDevice);
               executor.setOnPrintResultListener(new PrintExecutor.OnPrintResultListener() {
                    @Override
                    public void onResult(int errorCode) {
                          switch (errorCode) {
                                case PrintSocketHolder.ERROR_0:
                                     dialog.setState(R.string.printer_result_message_1);
                                     mSuccessPrinterSize++;
                                     Log.d("print", "onResult: 打印成功");
                                     mHandler.sendEmptyMessage(HANDLER_PRINT_SUCCESS);
                                 break;
                                 default:
                                      mHandler.sendEmptyMessage(HANDLER_PRINT_FAIL);
                                 break;
                    }
                });
                executor.doPrinterRequestAsync(maker);
            }
```
我在打印的结果回调里加上handler，就出现打印失败，注释掉就不会出现（handler里就做了一个Toast操作）
您好，如果您方便的话能加下我的QQ（1143171959）吗

**Comment by AlexMofer** [comment]
抱歉，现在才看到，问题有解决吗？方法setOnPrintResultListener的参数传进去，其实是生成了一个弱引用，你这样直接new出来的监听器，很可能不会回调，不过你这报错倒是有点意思，有具体的错误码吗？

**Comment by thundeGG** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
错误码不太记得了，我改成打印完这张然后间隔0.5秒打印下一张就好了



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                



    在2018年01月30日 01:36，Alex Mofer<notifications@github.com> 写道： 


抱歉，现在才看到，问题有解决吗？方法setOnPrintResultListener的参数传进去，其实是生成了一个弱引用，你这样直接new出来的监听器，很可能不会回调，不过你这报错倒是有点意思，有具体的错误码吗？
