### ISSUE TITLE
java对打印机的控制

### ISSUE THREAD

**Issue by aohanhongzhi** [AlexMofer/Printer#9]
我想请教一些问题，java控制打印机怎么弄双面打印之类的？控制打印机属性。ppt多合一的问题，pdf格式打印都很棘手。希望提供经验支持。感激不尽。

**Comment by AlexMofer** [comment]
我找的这份EPSON的ESC/POS命令集合里面貌似没包括双面打印及其他一些打印机属性控制指令。这是一份标准指令集，但其他打印指令集按理说也应该是支持此种方式的，但你需要找到指令写法。这个项目仅仅是做小票打印时整理出来的，应用场景也没有像你的需求那么宽泛。之后也没有再深入研究，因此也帮不到你什么。下面是指令集文档及对应实现的Java类，希望对你有所帮助：
https://github.com/AlexMofer/ProjectX/blob/master/printer/Commande%20ESCPOS.pdf
https://github.com/AlexMofer/ProjectX/blob/master/printer/src/main/java/am/util/printer/PrintCommands.java
